framework:
    rate_limiter:
        # Définition d'un limiteur nommé "login"
        login:
            policy: 'sliding_window'
            limit: 5          # 5 essais maximum
            interval: '1 minute' # par minute
