# --------------- DÉBUT COUCHE OS -------------------
FROM debian:stable-slim
# --------------- FIN COUCHE OS ---------------------

# MÉTADONNÉES DE L’IMAGE
LABEL version="1.0" maintainer="J. Lemouton <jolann.lemouton@etu.unicaen.fr>"